version: 2

jobs:
  build:
    working_directory: ~/blanda-api

    docker:
      - image: mizoguche/docker-java-aws-cli

    steps:
      - checkout

      - restore_cache:
          key: botlin-{{ checksum "botlin/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

      - run:
          name: Run Lint
          command: ./gradlew ktlint

      - run:
          name: Run Static Analysis
          command: ./gradlew detektCheck

      - run:
          name: Run Tests
          command: ./gradlew test

      - save_cache:
          key: botlin-{{ checksum "botlin/build.gradle" }}-{{ checksum ".circleci/config.yml" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
          paths:
            - "~/.gradle

      - run:
          name: Build
          command: ./gradlew build
